---

sudo: True
language: 'c'

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq genisoimage liblzma-dev syslinux

install: True

script:
  - 'git clone --depth 1 https://github.com/ipxe/ipxe.git ipxe_build'
  - 'cd ipxe_build/src ; make'
