site_name: netboot.xyz
pages:
- [index.md, Home]
- [boot_loaders.md, Booting with..., Extlinux/Grub]
- [boot_vbox.md, Booting with..., Virtual Box]
- [boot_vmware.md, Booting with..., VMware]
- [boot_drac.md, Booting with..., Dell DRAC]
- [boot_ilo.md, Booting with..., HP iLO]
