site_name: netboot.xyz
site_description: netboot all the things
site_author: netboot.xyz
site_url: http://netboot.xyz
docs_dir: docs
google_analytics: ['UA-68807-15', 'netboot.xyz']
pages:
- Home: 'index.md'
- Booting with...:
    - 'Dell DRAC': 'boot_drac.md'
    - 'Extlinux/Grub': 'boot_loaders.md'
    - 'HP iLO': 'boot_ilo.md'
    - 'Virtual Box': 'boot_vbox.md'
    - 'VMware': 'boot_vmware.md'
- Provider Usage:
    - 'Digital Ocean': 'usage_digitalocean.md'
