site_name: netboot.xyz
site_description: netboot all the things
site_author: netboot.xyz
site_url: http://netboot.xyz
docs_dir: docs
google_analytics: ['UA-68807-15', 'netboot.xyz']
pages:
- Home: 'index.md'
- Boot from...:
#    - 'Extlinux/Grub': 'boot_loaders.md'
    - 'iPXE': 'boot_ipxe.md'
    - 'ISO': 'boot_iso.md'
    - 'TFTP': 'boot_tftp.md'
    - 'USB': 'boot_usb.md'
#    - 'Virtual Box': 'boot_vbox.md'
#    - 'VMware': 'boot_vmware.md'
- Provider Usage:
    - 'Digital Ocean': 'usage_digitalocean.md'
    - 'Rackspace': 'usage_rackspace.md'
theme: flatly
