---
  - name: Retrieve pci.ids
    get_url:
      url: "{{ pciids_url }}"
      dest: "{{ netbootxyz_root }}/pci.ids"

  - name: Copy pciids_gen script to source dir
    copy:
      src: pciids_gen
      dest: "{{ netbootxyz_root }}/pciids_gen"
      mode: 0744

  - name: Convert pci.ids to pciids.ipxe
    shell: |
      ./pciids_gen pci.ids pciids.ipxe
    args:
      chdir: "{{ netbootxyz_root }}"
    tags:
    - skip_ansible_lint

  - name: Cleanup of files no longer needed
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ netbootxyz_root }}/pciids_gen"
      - "{{ netbootxyz_root }}/pci.ids"
